import { NextPage } from 'next'
import Head from 'next/head'

import { Canvas } from '@react-three/fiber'

import { Box } from '@/components'
import styles from '@/styles/Home.module.css'

const IndexPage: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Sculptor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Canvas shadows className={styles.canvas}>
          <ambientLight />
          <pointLight position={[10, 10, 10]} />
          <Box position={[-1.2, 0, 0]} />
          <Box position={[1.2, 0, 0]} />
        </Canvas>
      </main>
    </div>
  )
}

export default IndexPage
